# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 471)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: balck;\n"
"color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.push_cel = QtWidgets.QPushButton(self.centralwidget)
        self.push_cel.setGeometry(QtCore.QRect(20, 150, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_cel.setFont(font)
        self.push_cel.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: balck;\n"
"background-color: red\n"
";\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:red\n"
";\n"
"\n"
"}\n"
"\n"
"")
        self.push_cel.setObjectName("push_cel")
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        self.push_del.setGeometry(QtCore.QRect(220, 150, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_del.setFont(font)
        self.push_del.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: black;\n"
"\n"
"    background-color: red;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:red;\n"
"\n"
"}\n"
"")
        self.push_del.setObjectName("push_del")
        self.push_add_2 = QtWidgets.QPushButton(self.centralwidget)
        self.push_add_2.setGeometry(QtCore.QRect(320, 150, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_add_2.setFont(font)
        self.push_add_2.setStyleSheet("border-radius:20px;\n"
"color:black;\n"
"    background-color: yellow;\n"
"\n"
"")
        self.push_add_2.setObjectName("push_add_2")
        self.push_sub = QtWidgets.QPushButton(self.centralwidget)
        self.push_sub.setGeometry(QtCore.QRect(320, 210, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_sub.setFont(font)
        self.push_sub.setStyleSheet("border-radius:20px;\n"
"color:black;\n"
"    background-color: yellow;\n"
"\n"
"")
        self.push_sub.setObjectName("push_sub")
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        self.push_1.setGeometry(QtCore.QRect(20, 210, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_1.setFont(font)
        self.push_1.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.push_1.setObjectName("push_1")
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        self.push_3.setGeometry(QtCore.QRect(220, 210, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_3.setFont(font)
        self.push_3.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}\n"
"")
        self.push_3.setObjectName("push_3")
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        self.push_2.setGeometry(QtCore.QRect(120, 210, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_2.setFont(font)
        self.push_2.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_2.setObjectName("push_2")
        self.push_mult = QtWidgets.QPushButton(self.centralwidget)
        self.push_mult.setGeometry(QtCore.QRect(320, 270, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_mult.setFont(font)
        self.push_mult.setStyleSheet("border-radius:20px;\n"
"color:black;\n"
"    background-color: yellow;\n"
"\n"
"")
        self.push_mult.setObjectName("push_mult")
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        self.push_4.setGeometry(QtCore.QRect(20, 270, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_4.setFont(font)
        self.push_4.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_4.setObjectName("push_4")
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        self.push_6.setGeometry(QtCore.QRect(220, 270, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_6.setFont(font)
        self.push_6.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_6.setObjectName("push_6")
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        self.push_5.setGeometry(QtCore.QRect(120, 270, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_5.setFont(font)
        self.push_5.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_5.setObjectName("push_5")
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        self.push_7.setGeometry(QtCore.QRect(20, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_7.setFont(font)
        self.push_7.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_7.setObjectName("push_7")
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        self.push_9.setGeometry(QtCore.QRect(220, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_9.setFont(font)
        self.push_9.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_9.setObjectName("push_9")
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        self.push_8.setGeometry(QtCore.QRect(120, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_8.setFont(font)
        self.push_8.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_8.setObjectName("push_8")
        self.push_div = QtWidgets.QPushButton(self.centralwidget)
        self.push_div.setGeometry(QtCore.QRect(320, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_div.setFont(font)
        self.push_div.setStyleSheet("border-radius:20px;\n"
"color:black;\n"
"    background-color: yellow;\n"
"\n"
"")
        self.push_div.setObjectName("push_div")
        self.push_00 = QtWidgets.QPushButton(self.centralwidget)
        self.push_00.setGeometry(QtCore.QRect(20, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_00.setFont(font)
        self.push_00.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_00.setObjectName("push_00")
        self.push_equal = QtWidgets.QPushButton(self.centralwidget)
        self.push_equal.setGeometry(QtCore.QRect(320, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_equal.setFont(font)
        self.push_equal.setStyleSheet("border-radius:20px;\n"
"color:black;\n"
"    background-color: yellow;\n"
"\n"
"")
        self.push_equal.setObjectName("push_equal")
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        self.push_0.setGeometry(QtCore.QRect(120, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_0.setFont(font)
        self.push_0.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_0.setObjectName("push_0")
        self.push_period = QtWidgets.QPushButton(self.centralwidget)
        self.push_period.setGeometry(QtCore.QRect(220, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.push_period.setFont(font)
        self.push_period.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:black;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:yellow;\n"
"\n"
"}")
        self.push_period.setObjectName("push_period")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.push_cel.clicked.connect(self.clear)
        self.push_del.clicked.connect(self.delete)
        self.push_add_2.clicked.connect(self.add)
        self.push_sub.clicked.connect(self.sub)
        self.push_1.clicked.connect(self.mehtod1)
        self.push_3.clicked.connect(self.mehtod3)
        self.push_2.clicked.connect(self.mehtod2)
        self.push_mult.clicked.connect(self.mult)
        self.push_4.clicked.connect(self.mehtod4)
        self.push_6.clicked.connect(self.mehtod6)
        self.push_5.clicked.connect(self.mehtod5)
        self.push_7.clicked.connect(self.mehtod7)
        self.push_9.clicked.connect(self.mehtod9)
        self.push_8.clicked.connect(self.mehtod8)
        self.push_div.clicked.connect(self.div)
        self.push_00.clicked.connect(self.mehtod00)
        self.push_equal.clicked.connect(self.mehtodequal)
        self.push_0.clicked.connect(self.mehtod0)
        self.push_period.clicked.connect(self.mehtodperiod)


    def delete(self):

            text =self.label.text()
            self.label.setText(text[:len(text)-1])

    def mehtod1(self):

            text =self.label.text()
            self.label.setText(text+"1")

    def mehtod2(self):

            text =self.label.text()
            self.label.setText(text+"2")

    def mehtod3(self):

            text =self.label.text()
            self.label.setText(text+"3")

    def mehtod4(self):

            text =self.label.text()
            self.label.setText(text+"4")

    def mehtod5(self):

            text =self.label.text()
            self.label.setText(text+"5")

    def mehtod6(self):

            text =self.label.text()
            self.label.setText(text+"6")

    def mehtod7(self):

            text =self.label.text()
            self.label.setText(text+"7")

    def mehtod8(self):

            text =self.label.text()
            self.label.setText(text+"8")

    def mehtod9(self):

            text =self.label.text()
            self.label.setText(text+"9")

    def mehtod00(self):

            text =self.label.text()
            self.label.setText(text+"00")

    def add(self):

            text =self.label.text()
            self.label.setText(text+"+")

    def sub(self):

            text =self.label.text()
            self.label.setText(text+"-")

    def div(self):

            text =self.label.text()
            self.label.setText(text+"/")

    def mult(self):

            text =self.label.text()
            self.label.setText(text+"*")

    def mehtodequal(self):
              text=self.label.text()
              try:
                      ans=str(eval(text))
                      self.label.setText(ans)
              except:
                      self.label.setText("")

        #     if not(self.text or self.operation==""):
        #             val1=float(self.text)
        #             val2=float(self.label.text())
        #             self.text="0"
        #             if self.operation=="+":
        #                     self.text=val1+val2
        #             elif self.operation=="-":
        #                     self.text= val1 - val2
        #             elif self.operation=="*":
        #                     self.text= val1 * val2
        #             elif self.operation == "/":
        #                     self.text=val1 /val2
                     
        #             self.label.setText(str(self.text))

        #     text =self.label.text()
        #     self.label.setText(text+"=")

    def mehtodperiod(self):

            text =self.label.text()
            self.label.setText(text+".")

    def clear(self):

            text =self.label.text()
            self.label.setText("")

    def mehtod0(self):

            text =self.label.text()
            self.label.setText(text+"0")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Calc"))
        self.push_cel.setText(_translate("MainWindow", "Cel"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.push_del.setShortcut(_translate("MainWindow", "Backspace"))
        self.push_add_2.setText(_translate("MainWindow", "+"))
        self.push_add_2.setShortcut(_translate("MainWindow", "+"))
        self.push_sub.setText(_translate("MainWindow", "-"))
        self.push_sub.setShortcut(_translate("MainWindow", "-"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_1.setShortcut(_translate("MainWindow", "1"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.push_3.setShortcut(_translate("MainWindow", "3"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_2.setShortcut(_translate("MainWindow", "2"))
        self.push_mult.setText(_translate("MainWindow", "*"))
        self.push_mult.setShortcut(_translate("MainWindow", "*"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_4.setShortcut(_translate("MainWindow", "4"))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_6.setShortcut(_translate("MainWindow", "6"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_5.setShortcut(_translate("MainWindow", "5"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_7.setShortcut(_translate("MainWindow", "7"))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.push_9.setShortcut(_translate("MainWindow", "9"))
        self.push_8.setText(_translate("MainWindow", "8"))
        self.push_8.setShortcut(_translate("MainWindow", "8"))
        self.push_div.setText(_translate("MainWindow", "/"))
        self.push_div.setShortcut(_translate("MainWindow", "/"))
        self.push_00.setText(_translate("MainWindow", "00"))
        self.push_00.setShortcut(_translate("MainWindow", "0, 0"))
        self.push_equal.setText(_translate("MainWindow", "="))
        self.push_equal.setShortcut(_translate("MainWindow", "Enter"))
        self.push_0.setText(_translate("MainWindow", "0"))
        self.push_0.setShortcut(_translate("MainWindow", "0"))
        self.push_period.setText(_translate("MainWindow", "."))
        self.push_period.setShortcut(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
